# Generated by Django 4.0.5 on 2022-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('ad_id', models.TextField(blank=True, db_column='AD_ID', primary_key=True, serialize=False)),
                ('started_date', models.TextField(blank=True, db_column='Started_date', null=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('videos', models.TextField(blank=True, null=True)),
                ('videos_length', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('footer_text', models.TextField(blank=True, db_column='Footer_TEXT', null=True)),
                ('footer_action', models.TextField(blank=True, db_column='Footer_action', null=True)),
                ('page_name', models.TextField(blank=True, db_column='Page_name', null=True)),
                ('ad_occurance', models.IntegerField(blank=True, db_column='AD_occurance', null=True)),
                ('facebook_id', models.TextField(blank=True, db_column='Facebook_ID', null=True)),
                ('page_likes', models.IntegerField(blank=True, db_column='Page_likes', null=True)),
                ('instgram_id', models.TextField(blank=True, db_column='instgram_ID', null=True)),
                ('insta_followers', models.IntegerField(blank=True, null=True)),
                ('static_id', models.TextField(blank=True, db_column='static_ID', null=True)),
                ('ads_count', models.IntegerField(blank=True, db_column='Ads_count', null=True)),
                ('cumulative_ads_count', models.IntegerField(blank=True, null=True)),
                ('days', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('search_term', models.TextField(blank=True, null=True)),
                ('favourite', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ads',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='search_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.TextField()),
                ('search_type', models.TextField(choices=[('keyword', 'keyword'), ('page', 'page')])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'search_terms',
            },
        ),
        migrations.AddConstraint(
            model_name='search_term',
            constraint=models.UniqueConstraint(fields=('search_term', 'search_type'), name='only_one_search'),
        ),
    ]
