# Generated by Django 4.0.5 on 2022-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_pages',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
