# Generated by Django 4.0.5 on 2022-10-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_term',
            name='last_visited',
            field=models.TextField(blank=True, null=True),
        ),
    ]
