# Generated by Django 4.0.5 on 2022-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facebook_pages',
            fields=[
                ('static_ID', models.TextField(primary_key=True, serialize=False)),
                ('page_name', models.TextField()),
                ('favorites', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'facebook_pages',
            },
        ),
    ]
