# Generated by Django 4.0.5 on 2022-09-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_facebook_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebook_pages',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='search_term',
            name='static_ID',
            field=models.TextField(null=True),
        ),
    ]
