# Generated by Django 4.0.5 on 2022-10-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_facebook_pages_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_pages',
            name='ads_count',
            field=models.IntegerField(blank=True, db_column='Ads_count', null=True),
        ),
        migrations.AddField(
            model_name='facebook_pages',
            name='block_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebook_pages',
            name='facebook_id',
            field=models.TextField(blank=True, db_column='Facebook_ID', null=True),
        ),
        migrations.AddField(
            model_name='facebook_pages',
            name='insta_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebook_pages',
            name='instgram_id',
            field=models.TextField(blank=True, db_column='instgram_ID', null=True),
        ),
        migrations.AddField(
            model_name='facebook_pages',
            name='page_likes',
            field=models.IntegerField(blank=True, db_column='Page_likes', null=True),
        ),
        migrations.AddField(
            model_name='facebook_pages',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_pages',
            name='page_name',
            field=models.TextField(blank=True, db_column='Page_name', null=True),
        ),
    ]
