# Generated by Django 4.0.5 on 2022-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_facebook_pages_options_search_term_static_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_term',
            name='search_type',
            field=models.TextField(default='keyword'),
        ),
    ]
