# Generated by Django 4.0.5 on 2022-10-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_facebook_pages_ads_count_facebook_pages_block_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook_pages',
            name='page_name',
            field=models.TextField(),
        ),
    ]
