# Generated by Django 4.0.5 on 2022-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_alter_facebook_pages_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
