# Generated by Django 4.0.5 on 2022-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_alter_search_term_search_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_term',
            name='country',
            field=models.TextField(choices=[('ALL', 'EG'), ('ALL', 'EG')], default='ALL'),
        ),
    ]
