# Generated by Django 4.0.5 on 2022-10-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_ads_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_pages',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
