# Generated by Django 4.0.5 on 2022-09-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_search_term_country'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='search_term',
            name='only_one_search',
        ),
        migrations.AlterField(
            model_name='search_term',
            name='country',
            field=models.TextField(choices=[('ALL', 'ALL'), ('EG', 'EG')], default='ALL'),
        ),
        migrations.AddConstraint(
            model_name='search_term',
            constraint=models.UniqueConstraint(fields=('search_term', 'search_type', 'country'), name='only_one_search'),
        ),
    ]
