# Generated by Django 4.0.5 on 2022-09-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_alter_search_term_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={},
        ),
        migrations.AlterModelOptions(
            name='facebook_pages',
            options={},
        ),
    ]
