# Generated by Django 4.0.5 on 2022-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_search_term_search_term_only_one_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_term',
            name='search_term',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='search_term',
            name='search_type',
            field=models.TextField(choices=[('keyword', 'keyword'), ('page', 'page')]),
        ),
    ]
