# Generated by Django 4.0.5 on 2022-09-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_search_term_search_term_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'managed': True},
        ),
    ]
